---
    - name: Provision Web Servers
      hosts: tag_group_web
      tasks:
    
        - name: Install pip3
          apt:
            update_cache: yes
            name: python3-pip
            become: yes
    
        - name: Install python docker sdk
          shell: |
            pip3 install docker
          become: true
    
        - name: Install docker
          apt:
            name: docker.io
          become: true
    
        - name: Start Docker
          shell: |
            systemctl start docker
            systemctl enable docker
          become: true

        - name: Run image
          shell: docker run --name hello -dit -p 80:80 -p 443:443 fdoka/nginx-static-testS
          become: true